# Cellpose3 Denoising Configuration for NucWorm Benchmark
# This configuration enables both denoising and segmentation

# Experiment configuration
experiment:
  name: "cellpose3_denoising"
  save_dir: "./experiments/cellpose3_denoising"

# Device configuration
device: "cuda"  # Use "cuda" for GPU or "cpu" for CPU

# Data directories
data:
  input_dir: "/projects/weilab/gohaina/nucworm/outputs/data/neuropal_as_tiff"
  output_dir: "/projects/weilab/gohaina/nucworm/outputs/cellpose3_denoising"

# Data format
data_format:
  input_shape: "(C=3, Z, Y, X)"  # Actual input format: C=channels, Z=depth, Y=height, X=width
  target_shape: "(Z, C, Y, X)"  # Target format after transpose: Z=depth, C=channels, Y=height, X=width
  channels: 3  # Number of channels in the data (RGB)
  convert_to_grayscale: true  # Convert RGB to grayscale for Cellpose3
  rgb_weights: [0.299, 0.587, 0.114]  # RGB to grayscale conversion weights
  channel_mapping: "RGB"  # Channel mapping: 0=red, 1=green, 2=blue

# Cellpose3 denoising model configuration
model:
  model_type: "cyto3"  # or "nuclei" - using cyto3 for general cell segmentation
  restore_type: "denoise_cyto3"  # Enable denoising with cyto3 model
  gpu: true
  # Using Cellpose3 denoising model

# Processing configuration
processing:
  rescale: [1.0, 1.0, 1.0]  # [Z, Y, X] rescaling factors
  anisotropy: 2.0  # Default anisotropy (Z vs XY resolution ratio)
  
  # Dataset-specific anisotropy values
  dataset_anisotropy:
    yemini21: 3.57      # 0.75μm Z / 0.21μm XY
    nejatbakhsh20: 7.14 # 1.5μm Z / 0.21μm XY  
    wen20: 4.69         # 1.5μm Z / 0.32μm XY

# Segmentation configuration
segmentation:
  # Dataset-specific diameter values (in pixels)
  dataset_diameter:
    yemini21: 15        # 15 pixels in XY, 4 pixels in Z
    nejatbakhsh20: 15   # 15 pixels in XY, 2 pixels in Z
    wen20: 10           # 10 pixels in XY, 2 pixels in Z
  
  # Segmentation parameters
  flow_threshold: 0.4
  cellprob_threshold: 0.0
  min_size: 15
  stitch_threshold: 0.0

# Output configuration
output:
  save_masks: true
  save_flows: false  # Skip flows for denoising variant
  save_outlines: false  # Skip outlines for denoising variant
  save_denoised: true  # Save denoised images
  save_original: false  # Don't save original images

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
